import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://www.setting.live',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://www.setting.live/methode/setting-linkedin',
      lastModified: new Date('2026-03-22'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.setting.live/ressources',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.setting.live/ressources/setting-commercial-b2b',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.setting.live/ressources/closing-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.setting.live/ressources/discovery-call-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/gestion-objections-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/script-closing-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/prospection-linkedin-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/comment-devenir-setter-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/cout-setter-b2b-prix',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/setting-linkedin-definition',
      lastModified: new Date('2026-03-24'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.setting.live/ressources/ia-methode-humain-setting-linkedin',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/messages-linkedin-sans-reponse',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/signal-achat-linkedin',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/setter-b2b-definition',
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/challenger-sale-definition',
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/difference-setting-closing',
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/script-setting-linkedin',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/relance-linkedin-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/closer-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/a-propos',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/tarifs',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.setting.live/externaliser-prospection-linkedin',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    // /resultats temporairement retiré du sitemap (page en construction)
    // {
    //   url: 'https://www.setting.live/resultats',
    //   lastModified: new Date('2026-03-19'),
    //   changeFrequency: 'monthly',
    //   priority: 0.9,
    // },
    {
      url: 'https://www.setting.live/glossaire',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.setting.live/ressources/methodes-vente-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/methode-soncas',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/methode-spin-selling',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/qualification-leads-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/devenir-business-developer',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/setting-humain-vs-automatisation-linkedin',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/ressources/sdr-interne-vs-externalise',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.setting.live/mentions-legales',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.setting.live/politique-confidentialite',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ]
}
