import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://challengerslab.fr',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://challengerslab.fr/methode',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/methode/setting-linkedin',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/methode/setting-telephonique',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/methode/nurturing',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/ressources',
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/ressources/setting-commercial-b2b',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/ressources/closing-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://challengerslab.fr/ressources/discovery-call-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/gestion-objections-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/script-closing-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/prospection-linkedin-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/comment-devenir-setter-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/cout-setter-b2b-prix',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/ia-methode-humain-setting-linkedin',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/messages-linkedin-sans-reponse',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/signal-achat-linkedin',
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/setter-b2b-definition',
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/challenger-sale-definition',
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/difference-setting-closing',
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/script-setting-linkedin',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/relance-linkedin-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/closer-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/a-propos',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/tarifs',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://challengerslab.fr/externaliser-prospection-linkedin',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://challengerslab.fr/resultats',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://challengerslab.fr/glossaire',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://challengerslab.fr/ressources/methodes-vente-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/methode-soncas',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/methode-spin-selling',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/qualification-leads-b2b',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/devenir-business-developer',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/setting-humain-vs-automatisation-linkedin',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/ressources/sdr-interne-vs-externalise',
      lastModified: new Date('2026-03-19'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://challengerslab.fr/mentions-legales',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://challengerslab.fr/politique-confidentialite',
      lastModified: new Date('2026-03-18'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ]
}
